// ============================================================================
// FILE: test/services/auth_service_test.dart
// PURPOSE: Unit tests for AuthService
// ============================================================================

import 'package:flutter_test/flutter_test.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import '../../lib/services/auth_service.dart';
import '../../lib/data/models/user_model.dart';

// Mock classes are generated by mockito
void main() {
  late AuthService authService;
  late MockFirebaseAuth mockFirebaseAuth;
  late MockFirebaseFirestore mockFirebaseFirestore;
  late MockUserCredential mockUserCredential;
  late MockUser mockUser;

  setUp(() {
    mockFirebaseAuth = MockFirebaseAuth();
    mockFirebaseFirestore = MockFirebaseFirestore();
    mockUserCredential = MockUserCredential();
    mockUser = MockUser();
    
    authService = AuthService();
  });

  group('AuthService', () {
    test('should return auth state changes stream', () {
      // Arrange
      when(mockFirebaseAuth.authStateChanges).thenAnswer(
        (_) => Stream.value(mockUser),
      );

      // Act
      final stream = authService.authStateChanges;

      // Assert
      expect(stream, isA<Stream<User?>>());
    });

    test('should sign in with email and password', () async {
      // Arrange
      const email = 'test@example.com';
      const password = 'password123';
      when(mockUserCredential.user).thenReturn(mockUser);
      when(mockFirebaseAuth.signInWithEmailAndPassword(
        email: email,
        password: password,
      )).thenAnswer((_) async => mockUserCredential);

      // Act
      final result = await authService.signInWithEmailPassword(email, password);

      // Assert
      expect(result, equals(mockUserCredential));
      verify(mockFirebaseAuth.signInWithEmailAndPassword(
        email: email,
        password: password,
      )).called(1);
    });

    test('should create user with email and password', () async {
      // Arrange
      const email = 'test@example.com';
      const password = 'password123';
      when(mockUserCredential.user).thenReturn(mockUser);
      when(mockUser.sendEmailVerification()).thenAnswer((_) async {});
      when(mockFirebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      )).thenAnswer((_) async => mockUserCredential);

      // Act
      final result = await authService.createUserWithEmailPassword(email, password);

      // Assert
      expect(result, equals(mockUserCredential));
      verify(mockFirebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      )).called(1);
      verify(mockUser.sendEmailVerification()).called(1);
    });

    test('should check username availability', () async {
      // Arrange
      const username = 'testuser';
      final mockQuerySnapshot = MockQuerySnapshot();
      when(mockQuerySnapshot.docs).thenReturn([]);
      when(mockFirebaseFirestore.collection('users')).thenReturn(
        MockCollectionReference(),
      );
      when(mockFirebaseFirestore.collection('users').where(
        'username',
        isEqualTo: username.toLowerCase(),
      )).thenReturn(MockCollectionReference());
      when(mockFirebaseFirestore.collection('users').where(
        'username',
        isEqualTo: username.toLowerCase(),
      ).limit(1)).thenReturn(MockCollectionReference());
      when(mockFirebaseFirestore.collection('users').where(
        'username',
        isEqualTo: username.toLowerCase(),
      ).limit(1).get()).thenAnswer((_) async => mockQuerySnapshot);

      // Act
      final result = await authService.isUsernameAvailable(username);

      // Assert
      expect(result, isTrue);
    });

    test('should create user document', () async {
      // Arrange
      const uid = 'user123';
      const email = 'test@example.com';
      const username = 'testuser';
      final mockDocumentReference = MockDocumentReference();
      when(mockFirebaseFirestore.collection('users').doc(uid))
          .thenReturn(mockDocumentReference);
      when(mockDocumentReference.set(any)).thenAnswer((_) async {});

      // Act
      await authService.createUserDocument(uid, email, username);

      // Assert
      verify(mockDocumentReference.set(any)).called(1);
    });

    test('should get user data', () async {
      // Arrange
      const uid = 'user123';
      final mockDocumentSnapshot = MockDocumentSnapshot();
      when(mockDocumentSnapshot.exists).thenReturn(true);
      when(mockDocumentSnapshot.data()).thenReturn({
        'email': 'test@example.com',
        'username': 'testuser',
        'tier': 'free',
        'createdAt': Timestamp.fromDate(DateTime.now()),
        'lastSeen': Timestamp.fromDate(DateTime.now()),
        'settings': {},
        'limits': {},
      });
      when(mockFirebaseFirestore.collection('users').doc(uid).get())
          .thenAnswer((_) async => mockDocumentSnapshot);

      // Act
      final result = await authService.getUserData(uid);

      // Assert
      expect(result, isA<UserModel>());
      expect(result!.uid, equals(uid));
      expect(result.email, equals('test@example.com'));
    });

    test('should update username', () async {
      // Arrange
      const uid = 'user123';
      const username = 'newusername';
      final mockDocumentReference = MockDocumentReference();
      when(mockFirebaseFirestore.collection('users').doc(uid))
          .thenReturn(mockDocumentReference);
      when(mockDocumentReference.update({'username': username.toLowerCase()}))
          .thenAnswer((_) async {});

      // Act
      await authService.updateUsername(uid, username);

      // Assert
      verify(mockDocumentReference.update({'username': username.toLowerCase()}))
          .called(1);
    });

    test('should send password reset email', () async {
      // Arrange
      const email = 'test@example.com';
      when(mockFirebaseAuth.sendPasswordResetEmail(email: email))
          .thenAnswer((_) async {});

      // Act
      await authService.sendPasswordResetEmail(email);

      // Assert
      verify(mockFirebaseAuth.sendPasswordResetEmail(email: email)).called(1);
    });

    test('should sign out', () async {
      // Arrange
      when(mockFirebaseAuth.signOut()).thenAnswer((_) async {});

      // Act
      await authService.signOut();

      // Assert
      verify(mockFirebaseAuth.signOut()).called(1);
    });

    test('should delete account', () async {
      // Arrange
      const uid = 'user123';
      final mockDocumentReference = MockDocumentReference();
      when(mockFirebaseFirestore.collection('users').doc(uid))
          .thenReturn(mockDocumentReference);
      when(mockDocumentReference.delete()).thenAnswer((_) async {});
      when(mockUser.delete()).thenAnswer((_) async {});
      when(mockFirebaseAuth.currentUser).thenReturn(mockUser);

      // Act
      await authService.deleteAccount();

      // Assert
      verify(mockDocumentReference.delete()).called(1);
      verify(mockUser.delete()).called(1);
    });
  });
}

// Mock classes for testing
class MockQuerySnapshot extends Mock implements QuerySnapshot {}