// ============================================================================
// FILE: test/services/chat_service_test.dart
// PURPOSE: Unit tests for ChatService
// ============================================================================

import 'package:flutter_test/flutter_test.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import '../../lib/services/chat_service.dart';
import '../../lib/data/models/message_model.dart';
import '../../lib/data/models/chat_model.dart';

// Mock classes are generated by mockito
void main() {
  late ChatService chatService;
  late MockFirebaseFirestore mockFirebaseFirestore;
  late MockCollectionReference mockChatsCollection;
  late MockCollectionReference mockMessagesCollection;
  late MockDocumentReference mockChatDoc;
  late MockDocumentReference mockMessageDoc;

  setUp(() {
    mockFirebaseFirestore = MockFirebaseFirestore();
    mockChatsCollection = MockCollectionReference();
    mockMessagesCollection = MockCollectionReference();
    mockChatDoc = MockDocumentReference();
    mockMessageDoc = MockDocumentReference();
    
    chatService = ChatService();
  });

  group('ChatService', () {
    test('should create or get chat', () async {
      // Arrange
      const userId1 = 'user1';
      const userId2 = 'user2';
      const chatId = 'user1_user2';
      
      when(mockFirebaseFirestore.collection('chats'))
          .thenReturn(mockChatsCollection);
      when(mockChatsCollection.doc(chatId)).thenReturn(mockChatDoc);
      when(mockChatDoc.get()).thenAnswer((_) async => MockDocumentSnapshot());
      when(mockChatDoc.set(any)).thenAnswer((_) async {});

      // Act
      final result = await chatService.createOrGetChat(userId1, userId2);

      // Assert
      expect(result, equals(chatId));
      verify(mockChatsCollection.doc(chatId)).called(1);
    });

    test('should send message', () async {
      // Arrange
      const chatId = 'chat123';
      const senderId = 'user123';
      const text = 'Hello, world!';
      const retentionDays = 7;
      
      final mockMessagesCollection = MockCollectionReference();
      final mockMessageDoc = MockDocumentReference();
      
      when(mockFirebaseFirestore.collection('chats').doc(chatId))
          .thenReturn(mockChatDoc);
      when(mockChatDoc.collection('messages')).thenReturn(mockMessagesCollection);
      when(mockMessagesCollection.add(any)).thenAnswer((_) async => mockMessageDoc);
      when(mockFirebaseFirestore.collection('chats').doc(chatId).update(any))
          .thenAnswer((_) async {});

      // Act
      await chatService.sendMessage(chatId, senderId, text, retentionDays);

      // Assert
      verify(mockMessagesCollection.add(any)).called(1);
      verify(mockFirebaseFirestore.collection('chats').doc(chatId).update(any))
          .called(1);
    });

    test('should get messages stream', () {
      // Arrange
      const chatId = 'chat123';
      final mockQuery = MockQuery();
      final mockStream = MockStream();
      
      when(mockFirebaseFirestore.collection('chats').doc(chatId))
          .thenReturn(mockChatDoc);
      when(mockChatDoc.collection('messages')).thenReturn(mockMessagesCollection);
      when(mockMessagesCollection.orderBy('timestamp', descending: true))
          .thenReturn(mockQuery);
      when(mockQuery.limit(50)).thenReturn(mockQuery);
      when(mockQuery.snapshots()).thenReturn(mockStream);

      // Act
      final stream = chatService.getMessagesStream(chatId);

      // Assert
      expect(stream, isA<Stream<List<MessageModel>>());
    });

    test('should mark message as read', () async {
      // Arrange
      const chatId = 'chat123';
      const messageId = 'msg123';
      const userId = 'user123';
      
      when(mockFirebaseFirestore.collection('chats').doc(chatId))
          .thenReturn(mockChatDoc);
      when(mockChatDoc.collection('messages').doc(messageId))
          .thenReturn(mockMessageDoc);
      when(mockMessageDoc.update(any)).thenAnswer((_) async {});

      // Act
      await chatService.markMessageAsRead(chatId, messageId, userId);

      // Assert
      verify(mockMessageDoc.update({
        'readBy': anyNamed('FieldValue.arrayUnion'),
      })).called(1);
    });

    test('should add reaction to message', () async {
      // Arrange
      const chatId = 'chat123';
      const messageId = 'msg123';
      const emoji = '👍';
      const userId = 'user123';
      
      when(mockFirebaseFirestore.collection('chats').doc(chatId))
          .thenReturn(mockChatDoc);
      when(mockChatDoc.collection('messages').doc(messageId))
          .thenReturn(mockMessageDoc);
      when(mockMessageDoc.update(any)).thenAnswer((_) async {});

      // Act
      await chatService.addReaction(chatId, messageId, emoji, userId);

      // Assert
      verify(mockMessageDoc.update({
        'reactions.$emoji': anyNamed('FieldValue.arrayUnion'),
      })).called(1);
    });

    test('should get user chats stream', () {
      // Arrange
      const userId = 'user123';
      final mockQuery = MockQuery();
      final mockStream = MockStream();
      
      when(mockFirebaseFirestore.collection('chats')).thenReturn(mockChatsCollection);
      when(mockChatsCollection.where('participants', arrayContains: userId))
          .thenReturn(mockQuery);
      when(mockQuery.orderBy('lastMessageAt', descending: true))
          .thenReturn(mockQuery);
      when(mockQuery.snapshots()).thenReturn(mockStream);

      // Act
      final stream = chatService.getUserChatsStream(userId);

      // Assert
      expect(stream, isA<Stream<List<ChatModel>>());
    });

    test('should delete expired messages', () async {
      // Arrange
      final mockQuery = MockQuery();
      final mockQuerySnapshot = MockQuerySnapshot();
      final mockDoc = MockDocumentSnapshot();
      final mockBatch = MockWriteBatch();
      
      when(mockFirebaseFirestore.collectionGroup('messages')).thenReturn(mockQuery);
      when(mockQuery.where('expiresAt', isLessThan: anyNamed('isLessThan')))
          .thenReturn(mockQuery);
      when(mockQuery.get()).thenAnswer((_) async => mockQuerySnapshot);
      when(mockQuerySnapshot.docs).thenReturn([mockDoc]);
      when(mockFirebaseFirestore.batch()).thenReturn(mockBatch);
      when(mockBatch.commit()).thenAnswer((_) async {});

      // Act
      await chatService.deleteExpiredMessages();

      // Assert
      verify(mockBatch.commit()).called(1);
    });
  });
}

// Mock classes for testing
class MockQuery extends Mock implements Query {}
class MockStream extends Mock implements Stream<QuerySnapshot> {}
class MockWriteBatch extends Mock implements WriteBatch {}